### PR TITLE
feat: migrate ibc rate limiting

### LINKED ISSUE #188: Import IBC-RateLimit
cc Stride

### PR DESCRIPTION
**Pull request by johnletey**
This PR migrates the [IBC Rate Limiting](https://github.com/stride-labs/ibc-rate-limiting) module built by Stride Labs.

It migrates from @Reecepbcups' `feat/sdk-v50`, with a small addition from Noble's team to support app wiring ([commit](https://github.com/noble-assets/rate-limiting/commit/0f7c9279ffbb683526647f496566f9032df281d1)).

Closes #188.

### CODE REVIEW

**Comment by Reecepbcups** [comment]
I believe stride naming should be kept as they are the originator of the module. Similar to osmosis tokenfactory. changing proto namespace breaks all upstream tooling and apps and bots

**Comment by johnletey** [comment]
Reverted the query changes @Reecepbcups!

**Comment by Reecepbcups** [comment]
Thanks! I will review this once I talk with the stride team and also get them setup to coordinate. Ill review the diff from my v50 branch & this. I will be a little slow here as I just got back from vacation so might be more so a next week thing FYI

**Comment by Reecepbcups** [comment]
Reviewed and looks good! A few minor things I found in my diff review: https://github.com/Reecepbcups/ratelimitdif/pull/1

but I will handle in another PR. Thank you so so much for this addition! Really appreciate it a ton :heart:

**Review by Reecepbcups — APPROVED** [review]

**Pull request merged**
