### PR TITLE
deps(v7)!: bump IBC-Go v7.6.0

### PR DESCRIPTION
**Pull request by Reecepbcups**
Will tag as packet-forward-middleware v7.2.0

### CODE REVIEW

**Comment by Reecepbcups** [comment]
i think something with the golangci-lint server is down. Works for me locally, not remote (404) on download.

**Comment by jtieri** [comment]
> i think something with the golangci-lint server is down. Works for me locally, not remote (404) on download.

so weird it looks like it is still returning some errors. i didn't deep dive this but it almost looks like the things it is complaining about aren't even issues in this repo though but rather one of the dependencies?

**Comment by Reecepbcups** [comment]
@jtieri yep exactly! It may be due to some go1.XX version thing or linter version based on one of the deps.

**Comment by jtieri** [comment]
> @jtieri yep exactly! It may be due to some go1.XX version thing or linter version based on one of the deps.

what should we do with this, just approve and merge?

**Comment by Reecepbcups** [comment]
closing, do in the new v7 backport PR

**Pull request closed without merging**
