### PR TITLE
chore: sdk 50 upgrade for wasm hooks

### PR DESCRIPTION
**Pull request by faddat**
This PR is picking up where #163 left off, and is an attempt to complete the sdk v0.50.x upgrade for ibc-hooks.

This PR also upgrades to go v1.22.1

### CODE REVIEW

**Comment by jtieri** [comment]
cc @nicolaslara

**Comment by yan-wl** [comment]
Any idea on when this will be merged?

**Comment by faddat** [comment]
@yan-wl no idea.

**Comment by nicolaslara** [comment]
Haven't had a chance to review this. Ideally someone running a chain that uses v50 would test the integration before merging this.

**Comment by faddat** [comment]
What I know for sure is that it builds and passes tests, and builds in the Eve repo.

**Comment by nicolaslara** [comment]
yeah, should be fine. Just haven't had the time to review it myself.

**Comment by faddat** [comment]
kk, lmk if there's anything I can help you with on it.  I get ya on time sir.

**Pull request merged**
