### PR TITLE
core(deps): Upgrade ibc-hooks to IBC v8 and SDK v0.50.x

### PR DESCRIPTION
**Pull request by alexanderbez**

### CODE REVIEW

**Comment by disconsolate** [comment]
Hi, 
When is this branch planned to be merged into main?

**Comment by disconsolate** [comment]
Still waiting for this PR to be merged. Is there any estimation on when it will be done?

**Comment by faddat** [comment]
@disconsolate not really.  Both @alexanderbez and I took a swing at it.  

* https://github.com/eve-network/eve/issues/128

**Comment by Reecepbcups** [comment]
Closing this in favor of PR #166 which builds off it and passed CI test. Looks to be mostly just bumps and tweaks.

Have tagged osmosis as reviewers + added a new review me label as well

**Pull request closed without merging**
